### ISSUE TITLE
Extensive sweep is less extensive than normal sweep in some cases.

### ISSUE THREAD

**Issue by Zanthra** [tzwaan/factorio_balancers#5]
https://github.com/tzwaan/factorio_balancers/blob/9b101de521b6bebb61f11ecd8d6fe784749d0cea/factorio_balancers/balancer.py#L497-L503

Since range is not inclusive any tests with inputs equal to the number of outputs are skipped. A 3 splitter 4 to 2 balanced like this one reports that it has no bottlenecks with an extensive sweep, but reports the proper 50% throughput with a normal sweep. I would recommend adding 1 to the result in order to make the range inclusive.

0eNqdk9tqwzAMht9F125ZDrZTv0oZI9nEMCSKsdXREPzuy4FBtyXr3EsZ/s+fZGuEpr2g85YYzAj2tacA5jxCsO9Ut/MZDw7BgGXsQADV3Vzh1XkM4RBca5nRQxRg6Q2vYLIo/h1nX1NwvedDgy3fQPL4LACJLVtchZZieKFL10zXmeweS4DrwxTvabaYkOooBQxgivwo4+z4g5gnE/UdYrE/rt+slVRsk8pkN/nlJreJMsFNraRym6Qen9uOm378bXeIVUK31Z/dnpLdqm9u07deVsHcLJ6AD/RhSeRVVurypJXOnpRUMX4ChDw3tA==

> 
> ----:/mnt/c/Users/----/Downloads/factorio_balancers-0.2.9.tar/dist/factorio_balancers-0.2.9/bin$ python3.6 ./balancer_test -t -es --string 0eNqdk9tqwzAMht9F125ZDrZTv0oZI9nEMCSKsdXREPzuy4FBtyXr3EsZ/s+fZGuEpr2g85YYzAj2tacA5jxCsO9Ut/MZDw7BgGXsQADV3Vzh1XkM4RBca5nRQxRg6Q2vYLIo/h1nX1NwvedDgy3fQPL4LACJLVtchZZieKFL10zXmeweS4DrwxTvabaYkOooBQxgivwo4+z4g5gnE/UdYrE/rt+slVRsk8pkN/nlJreJMsFNraRym6Qen9uOm378bXeIVUK31Z/dnpLdqm9u07deVsHcLJ6AD/RhSeRVVurypJXOnpRUMX4ChDw3tA==
> Testing a 4 - 2 balancer.
>   Testing balance.
>    -- Output is balanced.
>    -- Input is balanced.
>   Testing balance using trickle.
>    -- Output is balanced with a trickle.
>    -- Input is balanced with a trickle.
>   Extensive throughput sweep
>    -- No bottlenecks with any combinations of any number of any number of inputs and outputs.
> {'lane_balancer': {'result': False}, 'balance.output': {'result': True}, 'balance.input': {'result': True}, 'balance.output.trickle': {'result': True}, 'balance.input.trickle': {'result': True}, 'throughput.unlimited': {'result': True}}
> ----:/mnt/c/Users/----/Downloads/factorio_balancers-0.2.9.tar/dist/factorio_balancers-0.2.9/bin$ python3.6 ./balancer_test -t -s --string 0eNqdk9tqwzAMht9F125ZDrZTv0oZI9nEMCSKsdXREPzuy4FBtyXr3EsZ/s+fZGuEpr2g85YYzAj2tacA5jxCsO9Ut/MZDw7BgGXsQADV3Vzh1XkM4RBca5nRQxRg6Q2vYLIo/h1nX1NwvedDgy3fQPL4LACJLVtchZZieK
> FL10zXmeweS4DrwxTvabaYkOooBQxgivwo4+z4g5gnE/UdYrE/rt+slVRsk8pkN/nlJreJMsFNraRym6Qen9uOm378bXeIVUK31Z/dnpLdqm9u07deVsHcLJ6AD/RhSeRVVurypJXOnpRUMX4ChDw3tA==
> Testing a 4 - 2 balancer.
>   Testing balance.
>    -- Output is balanced.
>    -- Input is balanced.
>   Testing balance using trickle.
>    -- Output is balanced with a trickle.
>    -- Input is balanced with a trickle.
>   Regular throughput sweep
>    -- At least one bottleneck exists that limits throughput to 50.0%.
> {'lane_balancer': {'result': False}, 'balance.output': {'result': True}, 'balance.input': {'result': True}, 'balance.output.trickle': {'result': True}, 'balance.input.trickle': {'result': True}, 'throughput.unlimited.candidate': {'result': False, 'message': 50.0}}

**Comment by tzwaan** [comment]
Ah, you're right. I'll fix it in the next version, whenever I get around to it. (been kind of busy lately).

You're also free to make a pull request, of course.
